---

- name: Install requirements
  package: 
     name: 
       - git
       - nodejs
       - yarn
     state: latest
  become: yes

- include_tasks: kubernetes.yml
- include_tasks: vscode.yml
- include_tasks: jetbrains_toolbox.yml
- include_tasks: devilbox.yml

- name: Make current user owner of global node_modules to allow installing of npm packages globally
  file:
    path: /home/{{ansible_user_id}}/.npm-global
    state: directory
    owner: '{{ansible_user_id}}'
    group: '{{ansible_user_id}}'
  become: yes

# Configure git
- name: Create or override .gitconfig file
  template:
     src: git.config.j2
     dest: /home/{{ansible_user_id}}/.gitconfig

- include_tasks: docker.yml